//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageTagWPF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizeDirectory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrganizeDirectory()
        {
            this.ParentDirectories = new HashSet<OrganizeDirectory>();
            this.ChildDirectories = new HashSet<OrganizeDirectory>();
            this.Tags = new HashSet<Tag>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public long IgnoreParent { get; set; }
        public long OrTags { get; set; }
        public long CopyOnly { get; set; }
        public Nullable<long> Rating { get; set; }
        public string Description { get; set; }
        public string ForeColor { get; set; }
        public string BackColor { get; set; }
        public long TheseTagsOnly { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganizeDirectory> ParentDirectories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganizeDirectory> ChildDirectories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
